version: "3.8"
services: 
    experter-job-app:
        build: .
        ports: 
            - "3000:3000"
        volumes: 
            - ./src:/app/src:ro
        # environment: 
        #     - REACT_APP_NAME=jobapp
        #     - NUMBER_PORT=job
        # env_file: 
        #     - ./.env            